plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.148'
}
version = mod_version
group = mod_group_id
base { archivesName = mod_id }
java.toolchain.languageVersion = JavaLanguageVersion.of(21)
repositories { mavenCentral() }
neoForge {
    version = neo_version
    parchment { mappingsVersion = parchment_mappings_version; minecraftVersion = parchment_minecraft_version }
    runs {
        client { client() }
        server { server(); programArgument '--nogui' }
        periodicServer {
            server(); gameDirectory = project.file('run-periodic')
            programArgument '--nogui'
            systemProperty 'spaceblocks.testServer', 'true'
        }
        periodicClient {
            client(); gameDirectory = project.file('run-periodic')
            programArguments.addAll '--quickPlaySingleplayer', 'PeriodicTest', '--width', '1280', '--height', '720'
            systemProperty 'spaceblocks.testClient', 'true'
        }
        packagedPeriodicClient {
            client(); loadedMods = []; gameDirectory = project.file('run-periodic')
            programArguments.addAll '--quickPlaySingleplayer', 'PeriodicTest', '--width', '1280', '--height', '720'
            systemProperty 'spaceblocks.testClient', 'true'
        }
        packagedPeriodicServer {
            server(); loadedMods = []; gameDirectory = project.file('run-periodic')
            programArgument '--nogui'
            systemProperty 'spaceblocks.testServer', 'true'
        }
    }
    mods { "${mod_id}" { sourceSet(sourceSets.main) } }
}
dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
tasks.named('test', Test) { useJUnitPlatform() }
sourceSets.test.compileClasspath += sourceSets.main.compileClasspath
sourceSets.test.runtimeClasspath += sourceSets.main.runtimeClasspath
var metadata = tasks.register('generateModMetadata', ProcessResources) {
    var properties = [minecraft_version_range:minecraft_version_range, neo_version:neo_version,loader_version_range:loader_version_range,mod_id:mod_id,mod_name:mod_name,mod_license:mod_license,mod_version:mod_version]
    inputs.properties properties
    expand properties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}
sourceSets.main.resources.srcDir metadata
neoForge.ideSyncTask metadata
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
tasks.named('jar', Jar) { from('LICENSE'); from('CREDITS.md'); from('docs/SPHERETEST-SOURCES.md') }
