modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="JonasHenriqueDev"
credits="Jeija / Spheretest and Minetest contributors. See CREDITS.md."
description='''
Finite periodic flat voxel map, rendered using Jeija's Spheretest complex exponential technique.
/planet large, /planet small, /planet leave, /planet fly, /planet info.
'''
[[mixins]]
config="spaceblocks.mixins.json"
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
